apiVersion: v1
kind: Service
metadata:
  name: "{{name}}"
  namespace: "{{namespace}}"
  labels:
    app.kubernetes.io/name: agor-shell-ssh
    app.kubernetes.io/component: ssh
    agor.io/worktree-id: "{{worktreeId}}"
    agor.io/user-id: "{{userId}}"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: agor-shell-pod
    agor.io/worktree-id: "{{worktreeId}}"
    agor.io/user-id: "{{userId}}"
  ports:
    - port: 22
      targetPort: 22
      name: ssh
      protocol: TCP
