apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agor.fullname" . }}-config
  labels:
    {{- include "agor.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.daemon.config | nindent 4 }}
